# Generated by Django 5.1.2 on 2024-10-30 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contact_delete_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calificación promedio de los usuarios, de 1 a 5', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
